AllCops:
  Exclude:
  - '**/vendor/**/*'

AbcSize:
  Enabled: false

BlockLength:
  Max: 100

Documentation:
  Enabled: false

LineLength:
  Max: 150

MethodLength:
  Max: 20

MutableConstant:
  Enabled: false

Style/StringLiterals:
  Exclude:
  - spec/fixtures/steps/*.rb

UnifiedInteger:
  Enabled: false
