language: ruby
rvm:
  - 2.0.0
  - 2.1.*
  - 2.2.*
gemfile:
  - Gemfile
  - rspec-2.99.x.gemfile
matrix:
  allow_failures:
    - gemfile: Gemfile
script: bundle exec rake spec && bundle exec rspec --tag before_load spec
