language: ruby
cache: bundler
rvm:
  - 2.2.*
  - 2.3.*
  - 2.4.*
  - 2.5.0
gemfile:
  - Gemfile
  - gemfiles/rspec-3.5.x.gemfile
  - gemfiles/rspec-3.6.x.gemfile
  - gemfiles/rspec-3.7.x.gemfile
matrix:
  allow_failures:
    - gemfile: Gemfile

script: bundle exec rake spec && bundle exec rspec --tag before_load spec
